# version: 0.0 오타시 에러발생
# ->The deployment failed because an invalid version value () was entered in the application specification file. Make sure your AppSpec file specifies "0.0" as the version, and then try again.
version: 0.0
os: linux
files:
  # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 (/ 루트경로를 지정하면 전체파일 대상)
  - source: /
    #destination: /home/ec2-user/app/step2/zip/
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes
# CodeDeploy에서 EC2 서버로 넘겨준 파일들은 모두 ec2-user 권한을 갖도록 설정

permission:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: e2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정 - Jar파일 복사된 이후 차례대로 스크립스 실행됨
# ApplicationStart라는 단계에서 deploy.sh를 ec20-user 권한으로 실행하게 함
hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있지 않은 스프링부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: deploy.sh #엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부트를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh #새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user